version: '3.8'

services:
  pgbouncer:
    build:
      dockerfile: Dockerfile
      context: ./
    command: sleep infinity
    volumes:
      - .bash_history:/root/.bash_history
      - ../..:/workspace:cached

    network_mode: service:db

  db:
    image: postgres:16.0
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data

    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  postgres-data:
